"""添加表数量和连接状态字段

Revision ID: 9b82f1a0e1ae
Revises: 9ce74f9348b3
Create Date: 2025-04-25 09:41:42.735784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b82f1a0e1ae'
down_revision = '9ce74f9348b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='会话标题',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=True)
        batch_op.alter_column('model_id',
               existing_type=mysql.INTEGER(),
               comment='使用的模型ID',
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否活跃',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_count', sa.Integer(), nullable=True, comment='表数量'))
        batch_op.add_column(sa.Column('connection_status', sa.String(length=20), nullable=True, comment='连接状态'))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='数据源名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='描述信息',
               existing_nullable=True)
        batch_op.alter_column('ds_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='数据源类型',
               existing_nullable=False)
        batch_op.alter_column('host',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='服务器主机名/地址',
               existing_nullable=False)
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(),
               comment='端口号',
               existing_nullable=False)
        batch_op.alter_column('database',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='数据库名称',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='密码(加密存储)',
               existing_nullable=False)
        batch_op.alter_column('options',
               existing_type=mysql.JSON(),
               comment='其他连接选项',
               existing_nullable=True)
        batch_op.alter_column('include_views',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否包含视图',
               existing_nullable=True)
        batch_op.alter_column('format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='模式名称',
               existing_nullable=True)
        batch_op.alter_column('selected_fields',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='选择字段',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               comment='会话ID',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='消息角色(user/assistant/system)',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='消息内容',
               existing_nullable=False)
        batch_op.alter_column('sql_query',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='生成的SQL查询语句',
               existing_nullable=True)
        batch_op.alter_column('query_results',
               existing_type=mysql.JSON(),
               comment='查询结果',
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='错误信息',
               existing_nullable=True)
        batch_op.alter_column('tokens_used',
               existing_type=mysql.INTEGER(),
               comment='使用的token数量',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='模型名称',
               existing_nullable=False)
        batch_op.alter_column('provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='模型提供商',
               existing_nullable=False)
        batch_op.alter_column('model_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='模型类型',
               existing_nullable=False)
        batch_op.alter_column('api_base',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='API基础URL',
               existing_nullable=True)
        batch_op.alter_column('api_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='API密钥(加密存储)',
               existing_nullable=True)
        batch_op.alter_column('api_version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='API版本',
               existing_nullable=True)
        batch_op.alter_column('temperature',
               existing_type=mysql.FLOAT(),
               comment='温度参数',
               existing_nullable=True)
        batch_op.alter_column('max_tokens',
               existing_type=mysql.INTEGER(),
               comment='最大生成token数',
               existing_nullable=True)
        batch_op.alter_column('is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否默认模型',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否激活',
               existing_nullable=True)
        batch_op.alter_column('parameters',
               existing_type=mysql.JSON(),
               comment='其他模型参数',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               comment='电子邮件',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否激活',
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否管理员',
               existing_nullable=True)
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               comment='最后登录时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后登录时间',
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否管理员',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               comment=None,
               existing_comment='电子邮件',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('parameters',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='其他模型参数',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=True)
        batch_op.alter_column('is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否默认模型',
               existing_nullable=True)
        batch_op.alter_column('max_tokens',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='最大生成token数',
               existing_nullable=True)
        batch_op.alter_column('temperature',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='温度参数',
               existing_nullable=True)
        batch_op.alter_column('api_version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='API版本',
               existing_nullable=True)
        batch_op.alter_column('api_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='API密钥(加密存储)',
               existing_nullable=True)
        batch_op.alter_column('api_base',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='API基础URL',
               existing_nullable=True)
        batch_op.alter_column('model_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='模型类型',
               existing_nullable=False)
        batch_op.alter_column('provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='模型提供商',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('tokens_used',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='使用的token数量',
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
        batch_op.alter_column('query_results',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='查询结果',
               existing_nullable=True)
        batch_op.alter_column('sql_query',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='生成的SQL查询语句',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='消息角色(user/assistant/system)',
               existing_nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)

    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('selected_fields',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='选择字段',
               existing_nullable=True)
        batch_op.alter_column('format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='模式名称',
               existing_nullable=True)
        batch_op.alter_column('include_views',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否包含视图',
               existing_nullable=True)
        batch_op.alter_column('options',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='其他连接选项',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='密码(加密存储)',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('database',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='数据库名称',
               existing_nullable=False)
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='端口号',
               existing_nullable=False)
        batch_op.alter_column('host',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='服务器主机名/地址',
               existing_nullable=False)
        batch_op.alter_column('ds_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='数据源类型',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='描述信息',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='数据源名称',
               existing_nullable=False)
        batch_op.drop_column('connection_status')
        batch_op.drop_column('table_count')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否活跃',
               existing_nullable=True)
        batch_op.alter_column('model_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='使用的模型ID',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='会话标题',
               existing_nullable=True)

    # ### end Alembic commands ###
